version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433" # Exposes the SQL Server port to the host
    environment:
      ACCEPT_EULA: "Y"         # Accepts the SQL Server EULA
      SA_PASSWORD: "YourPassword123"  # Sets the SA (admin) user password
    volumes:
      - sql_data:/var/opt/mssql    # Persist SQL Server data
      - ./init-scripts:/init-scripts # Mounts the initialization scripts
    entrypoint: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 15 &&
      for file in /init-scripts/*.sql; do
        echo Running $file;
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourPassword123 -i $file;
      done;
      wait
      "

volumes:
  sql_data: # Named volume for SQL Server data